### ISSUE TITLE
Upgrading to v3.0 seems to be incompatible with Sapper Framework

### ISSUE THREAD

**Issue by clhenrick** [sveltejs/svelte-loader#198]
I have Svelte app built with the Sapper framework. When I attempt to upgrade `svelte-loader` to a version >= 3.0 the following error is thrown in the terminal and the app will not load:

```
TypeError: _internal_App_svelte__WEBPACK_IMPORTED_MODULE_9__.default.render is not a function
    at eval (webpack:///./src/node_modules/@sapper/server.mjs?:4706:106)
    at Generator.next (<anonymous>)
    at fulfilled (webpack:///./src/node_modules/@sapper/server.mjs?:147:58)
    at runNextTicks (internal/process/task_queues.js:60:5)
    at processImmediate (internal/timers.js:437:9)
```

Verified that v2.13.6 does not break the build.

Curious if anyone else has experienced this and if there's a work around, thanks.

**Comment by maxlath** [comment]
@clhenrick do you still have this problem? If not, as [Sapper is now deprecated](https://github.com/sveltejs/sapper), we could probably close this issue

**Comment by clhenrick** [comment]
@maxlath thanks and yes I still have this problem. I understand that Svelte Kit is the Svelte framework moving forward but I imagine there still others supporting Sapper who are unable to migrate to Svelte Kit.

**Comment by MichielEng** [comment]
I have this problem as well. I have plans to move to svelte-kit, but project schedule has not allowed it yet.

**Comment by benmccann** [comment]
We're no longer supporting Sapper. You'll have to stay on an old version of `svelte-loader` until you're able to migrate off Sapper
