### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by ericyd** [sveltejs/svelte-loader#25]
I cloned this repo, installed dependencies for the webpack2 example, and ran `npm run bundle`.  This was the output of the error message.  I was getting this same error when trying to use the loader on a personal project, but wasn't sure if I had mis-configured something.

I am running Linux Mint 18, 64-bit.
```
/home/eric/repos/svelte-loader/example/webpack2/webpack.config.js:1
(function (exports, require, module, __filename, __dirname) { const { readFileSync } = require('fs');
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireConfig (/home/eric/repos/svelte-loader/example/webpack2/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/eric/repos/svelte-loader/example/webpack2/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)
```

I tried changing line 1 of the `webpack.config.js` file to read as follows:

`const readFileSync = require('fs').readFileSync;`

This was the new error message when I retried the bundle:
```
loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: c658534462e32519a92a
Version: webpack 2.5.1
Time: 723ms
   Asset     Size  Chunks             Chunk Names
index.js  10.5 kB       0  [emitted]  index
   [0] ./src/index.js 248 bytes {0} [built]
   [1] ./src/counter.html 2.69 kB {0} [built] [failed] [1 error]
   [2] multi ./src/index.js 28 bytes {0} [built]

ERROR in ./src/counter.html
Module build failed: SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at loadLoader (/home/eric/repos/svelte-loader/example/webpack2/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/home/eric/repos/svelte-loader/example/webpack2/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/eric/repos/svelte-loader/example/webpack2/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/eric/repos/svelte-loader/example/webpack2/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/home/eric/repos/svelte-loader/example/webpack2/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/home/eric/repos/svelte-loader/example/webpack2/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/eric/repos/svelte-loader/example/webpack2/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/home/eric/repos/svelte-loader/example/webpack2/node_modules/webpack/lib/NormalModule.js:179:3)
    at NormalModule.build (/home/eric/repos/svelte-loader/example/webpack2/node_modules/webpack/lib/NormalModule.js:268:15)
    at Compilation.buildModule (/home/eric/repos/svelte-loader/example/webpack2/node_modules/webpack/lib/Compilation.js:146:10)
    at factoryCallback (/home/eric/repos/svelte-loader/example/webpack2/node_modules/webpack/lib/Compilation.js:329:11)
    at /home/eric/repos/svelte-loader/example/webpack2/node_modules/webpack/lib/NormalModuleFactory.js:253:5
    at /home/eric/repos/svelte-loader/example/webpack2/node_modules/webpack/lib/NormalModuleFactory.js:99:14
    at /home/eric/repos/svelte-loader/example/webpack2/node_modules/tapable/lib/Tapable.js:204:11
    at NormalModuleFactory.<anonymous> (/home/eric/repos/svelte-loader/example/webpack2/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/home/eric/repos/svelte-loader/example/webpack2/node_modules/tapable/lib/Tapable.js:208:13)
    at /home/eric/repos/svelte-loader/example/webpack2/node_modules/webpack/lib/NormalModuleFactory.js:74:11
    at /home/eric/repos/svelte-loader/example/webpack2/node_modules/webpack/lib/NormalModuleFactory.js:205:8
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)
 @ ./src/index.js 3:0-32
 @ multi ./src/index.js
```

**Comment by jihchi** [comment]
Do you use the JS compiler such as Babel to compile your svelte code?

It seems like you're using ES6 syntax and svalte-loader can't  recognize it.

FYI: https://github.com/jihchi/svelte-starter/blob/master/webpack.config.babel.js#L19

**Comment by ericyd** [comment]
Yes, I used the config file from this repository's webpack2 example directory, which includes the babel loader. I did try removing html from the test for the babel loader, but the problem was the same.

**Comment by ericyd** [comment]
I think this is likely due to the version of node I am using.  I am not at my main computer right now, but I believe I was using 7.x.  I just tried with 6.9 on a windows box and it worked fine.  I'm going to keep investigating, it would be nice to get it compatible with something higher than 6.x.

**Comment by ericyd** [comment]
This error was caused by using node 4.7.3.  Setting my node default to 6 solved the issue.
