### ISSUE TITLE
options.filename undefined in 2.13.1

### ISSUE THREAD

**Issue by onip** [sveltejs/svelte-loader#79]
```
ERROR in ./src/uis/control/App.svelte
Module build failed (from ./node_modules/svelte-loader/index.js):
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at basename (path.js:1294:5)
    at sanitize (/home/onip/workspace/pantobot3d/calibration-ui/node_modules/svelte-loader/index.js:57:9)
    at Object.module.exports (/home/onip/workspace/pantobot3d/calibration-ui/node_modules/svelte-loader/index.js:134:36)
```

```
$ npm ls svelte
calibration-ui@1.0.0 /home/onip/workspace/pantobot3d/calibration-ui
└── svelte@2.16.1 
```

the issue seems to have originated from commit [f919ccf0c9b9d3d615269f54c33ff3f3086ef1d0](https://github.com/sveltejs/svelte-loader/commit/f919ccf0c9b9d3d615269f54c33ff3f3086ef1d0)

**Comment by Rich-Harris** [comment]
whoops! thanks, should be fixed in 2.13.2 by 9f9df9d31ed12fb75e59bf302115e331dfa108fd
